site_name: Bayesian Analysis Recipes

theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'
  logo:
    icon: 'library_books'

plugins:
  - search
  - mknotebooks:
      execute: false
      write_markdown: true
      timeout: 600

# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.attr_list

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

repo_name: 'ericmjl/bayesian-analysis-recipes'
repo_url: 'https://github.com/ericmjl/bayesian-analysis-recipes'

extra:
  social:
    - type: 'envelope'
      link: 'http://www.shortwhale.com/ericmjl'
    - type: 'github'
      link: 'https://github.com/ericmjl'
    - type: 'twitter'
      link: 'https://twitter.com/ericmjl'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/ericmjl'
